pages:
  image: node:lts  # uses Docker image to build site
  before_script:
    - npm ci  # install dependencies
  script:
    - npm run build
  artifacts:
    paths:
      - public  # contains built files to be published
    exclude:
      - assets
  publish: public
  only:
    - main